export const places = {
    googleMapSettings: {
        center: {
            lat: 45.738245,
            lng: 4.814722,
        },
        zoom: 16,
        minZoom: 15,
        maxZoom: 19,
        styles: [
            {
                featureType: 'poi',
                stylers: [
                    {visibility: 'off'},
                ],
            },
        ],
    },
    types: [
        {
            key: 'restaurant',
            value: 'Restaurant',
        },
        {
            key: 'foodcourt',
            value: 'Food Court',
        },
        {
            key: 'cantine',
            value: 'Cantine',
        },
        {
            key: 'epicerie',
            value: 'Épicerie',
        },
        {
            key: 'boulangerie',
            value: 'Boulangerie',
        },
        {
            key: 'fast',
            value: 'Fast Food',
        },
        {
            key: 'truck',
            value: 'Food Truck',
        },
        {
            key: 'sandwich',
            value: 'Sandwicherie',
        },
        {
            key: 'bistrot',
            value: 'Bistrot',
        },
        {
            key: 'brasserie',
            value: 'Brasserie',
        },
        {
            key: 'commercial',
            value: 'Centre Commercial',
        },
    ],
    options: [
        {
            key: 'place',
            value: 'Sur Place',
        },
        {
            key: 'emporte',
            value: 'À Emporter',
        },
        {
            key: 'livraison',
            value: 'Livraison',
        },
    ],
    days: [
        {
            key: 'lundi',
            value: 'Lundi',
        },
        {
            key: 'mardi',
            value: 'Mardi',
        },
        {
            key: 'mercredi',
            value: 'Mercredi',
        },
        {
            key: 'jeudi',
            value: 'jeudi',
        },
        {
            key: 'vendredi',
            value: 'Vendredi',
        },
        {
            key: 'samedi',
            value: 'Samedi',
        },
        {
            key: 'dimanche',
            value: 'Dimanche',
        },
    ],
    places: [
        {
            id: 'niji',
            name: 'Niji',
            latitude: 45.738269,
            longitude: 4.814711,
            description: 'J\'ai ma bouffe !',
            distanceToNiji: 0,
            type: null,
            keywords: [],
            options: [],
            openingDays: ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche'],
        },
        {
            id: 'fratelli',
            name: 'Fratelli',
            latitude: 45.738027,
            longitude: 4.814755,
            description: 'Bianca d\'alba !',
            distanceToNiji: 10,
            type: 'restaurant',
            keywords: ['italien', 'pizza', 'pate', 'tiramisu', 'plat du jour', 'terrasse'],
            options: ['place', 'emporte'],
            openingDays: ['mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi'],
        },
        {
            id: 'dejbox',
            name: 'Dejbox',
            latitude: 45.738137,
            longitude: 4.814987,
            description: 'Parfait pour manger rapidement',
            distanceToNiji: 10,
            type: 'cantine',
            keywords: ['salade', 'pate', 'plat du jour'],
            options: ['livraison'],
            openingDays: ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche'],
        },
        {
            id: 'selcius',
            name: 'Selcius',
            latitude: 45.738894,
            longitude: 4.814791,
            description: 'Plus gourmet que gourmand',
            distanceToNiji: 90,
            type: 'restaurant',
            keywords: ['tapas', 'pate', 'risotto', 'poisson', 'viande', 'terrasse'],
            options: ['place'],
            openingDays: ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche'],
        },
        {
            id: 'o-quai-49',
            name: 'Ô Quai 49',
            latitude: 45.737701,
            longitude: 4.814686,
            description: 'Wagon bar en bord de Sâone',
            distanceToNiji: 90,
            type: 'truck',
            keywords: ['sandwich', 'salade', 'terrasse'],
            options: ['place', 'emporte'],
            openingDays: ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi'],
        },
        {
            id: 'dock-40',
            name: 'Dock 40',
            latitude: 45.739762,
            longitude: 4.814390,
            description: 'Plat du jour 12€<br>Entrée-plat ou Plat-dessert 15€<br>Menu complet 18€',
            distanceToNiji: 190,
            type: 'restaurant',
            keywords: ['francais', 'poisson', 'viande', 'terrasse', 'buffet'],
            options: ['place'],
            openingDays: ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche'],
        },
        {
            id: 'le-moulin',
            name: 'Le Moulin',
            latitude: 45.734090,
            longitude: 4.815726,
            description: 'La charette du Moulin<br>(Salade à composer)',
            distanceToNiji: 500,
            type: 'truck',
            keywords: ['salade', 'soupe', 'vegetarien', 'healthy'],
            options: ['livraison'],
            openingDays: ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche'],
        },
        {
            id: 'woko',
            name: 'Woko',
            latitude: 45.741058,
            longitude: 4.817359,
            description: 'Wok Vietnamien',
            distanceToNiji: 500,
            type: 'fast',
            keywords: ['vietnamien', 'wok'],
            options: ['place', 'emporte'],
            openingDays: ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche'],
        },
        {
            id: 'piada',
            name: 'Piada',
            latitude: 45.741107,
            longitude: 4.817229,
            description: 'Les naans à l\'Italienne',
            distanceToNiji: 500,
            type: 'fast',
            keywords: ['piadina', 'naan', 'galette', 'italien', 'tiramisu'],
            options: ['place', 'emporte'],
            openingDays: ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche'],
        },
        {
            id: 'steak-n-shake',
            name: 'Steak \'n Shake',
            latitude: 45.741408,
            longitude: 4.816396,
            description: 'Les burgers à l\'américaine, avec des bons milkshakes',
            distanceToNiji: 500,
            type: 'fast',
            keywords: ['burger', 'frite', 'milkshake'],
            options: ['place', 'emporte'],
            openingDays: ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche'],
        },
        {
            id: 'subway',
            name: 'Subway',
            latitude: 45.741464,
            longitude: 4.816246,
            description: 'Pour manger rapidement quand y a trop de monde à Macdo',
            distanceToNiji: 500,
            type: 'fast',
            keywords: ['sandwich', 'donut', 'cookie'],
            options: ['emporte'],
            openingDays: ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche'],
        },
        {
            id: 'go-mex',
            name: 'Go Mex',
            latitude: 45.741500,
            longitude: 4.816120,
            description: 'Mexicain !',
            distanceToNiji: 500,
            type: 'fast',
            keywords: ['mexicain', 'burrito', 'tacos', 'quesadillas'],
            options: ['emporte'],
            openingDays: ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche'],
        },
        {
            id: 'hanoi-caphe',
            name: 'Hanoï Cà Phê',
            latitude: 45.741737,
            longitude: 4.815785,
            description: 'Restaurant Vietnamien',
            distanceToNiji: 500,
            type: 'restaurant',
            keywords: ['vietnamien', 'nem', 'pho', 'bo bun', 'pad thai', 'terrasse'],
            options: ['place', 'emporte'],
            openingDays: ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche'],
        },
        {
            id: 'la-criee',
            name: 'La Criée',
            latitude: 45.741852,
            longitude: 4.815881,
            description: 'Restaurant de poissons et fruits de mer',
            distanceToNiji: 500,
            type: 'restaurant',
            keywords: ['poisson', 'moule', 'terrasse'],
            options: ['place'],
            openingDays: ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche'],
        },
        {
            id: 'le-paradis-du-fruit',
            name: 'Le Paradis du Fruit',
            latitude: 45.741744,
            longitude: 4.816232,
            description: 'Restaurant healthy et bar à fruit',
            distanceToNiji: 500,
            type: 'restaurant',
            keywords: ['healty', 'fruit', 'vegetarien'],
            options: ['place'],
            openingDays: ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche'],
        },
        {
            id: 'amelie-crepes',
            name: 'Amélie Crêpes',
            latitude: 45.740989,
            longitude: 4.817533,
            description: 'Galettes Bretonnes',
            distanceToNiji: 500,
            type: 'restaurant',
            keywords: ['galette'],
            options: ['place'],
            openingDays: ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche'],
        },
        {
            id: 'cafe-perche',
            name: 'Café Perché',
            latitude: 45.740811,
            longitude: 4.817935,
            description: 'Des bonnes tartines après une séance d\'escalade',
            distanceToNiji: 500,
            type: 'fast',
            keywords: ['salade', 'sandwich', 'tartine'],
            options: ['place', 'emporte'],
            openingDays: ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche'],
        },
        {
            id: 'sushi-shop',
            name: 'Sushi Shop',
            latitude: 45.741421,
            longitude: 4.817143,
            description: 'Sushi ouh haha',
            distanceToNiji: 500,
            type: 'restaurant',
            keywords: ['japonais', 'sushi', 'maki', 'chirashi', 'terrasse'],
            options: ['place', 'emporte'],
            openingDays: ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche'],
        },
        {
            id: 'razowski',
            name: 'Razowski',
            latitude: 45.741334,
            longitude: 4.817418,
            description: 'Pour les grosses dalles',
            distanceToNiji: 500,
            type: 'restaurant',
            keywords: ['burger', 'viande', 'poulet', 'salade', 'americain', 'bob', 'terrasse'],
            options: ['place'],
            openingDays: ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche'],
        },
        {
            id: 'hippopotamus',
            name: 'Hippopotamus',
            latitude: 45.740982,
            longitude: 4.818336,
            description: 'Steak house',
            distanceToNiji: 500,
            type: 'restaurant',
            keywords: ['burger', 'viande', 'salade', 'terrasse'],
            options: ['place'],
            openingDays: ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche'],
        },
        {
            id: 'vapiano',
            name: 'Vapiano',
            latitude: 45.740841,
            longitude: 4.818707,
            description: 'Spécialités Italiennes à emporter',
            distanceToNiji: 500,
            type: 'cantine',
            keywords: ['italien', 'pate', 'lasagne', 'pizza'],
            options: ['place', 'emporte'],
            openingDays: ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche'],
        },
        {
            id: 'cellerier',
            name: 'Cellerier',
            latitude: 45.740861,
            longitude: 4.818622,
            description: 'C\'est bon pour les petites faims en recherche d\'équilibre. Plats du jour variés autour des 9€',
            distanceToNiji: 500,
            type: 'epicerie',
            keywords: ['traiteur', 'viande', 'poisson', 'salade', 'patisserie', 'madeleine', 'sandwich', 'quiche'],
            options: ['emporte'],
            openingDays: ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche'],
        },
        {
            id: 'paul',
            name: 'Paul',
            latitude: 45.740763,
            longitude: 4.818787,
            description: 'Boulangerie, patisserie, sandwicherie',
            distanceToNiji: 500,
            type: 'sandwich',
            keywords: ['boulangerie', 'patisserie', 'sandwich', 'pizza'],
            options: ['emporte'],
            openingDays: ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche'],
        },
        {
            id: 'carrefour',
            name: 'Carrefour',
            latitude: 45.740706,
            longitude: 4.818090,
            description: 'Centre commercial avec rayon traiteur',
            distanceToNiji: 500,
            type: 'commercial',
            keywords: ['carrefour', 'traiteur'],
            options: ['emporte'],
            openingDays: ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche'],
        },
        {
            id: 'mcdo',
            name: 'McDonald\'s',
            latitude: 45.741577,
            longitude: 4.816712,
            description: 'Restaurant préféré de Théo',
            distanceToNiji: 500,
            type: 'fast',
            keywords: ['mcdo', 'macdo', 'mcdonald', 'burger', 'frite', 'terrasse'],
            options: ['place', 'emporte'],
            openingDays: ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche'],
        },
        {
            id: 'burger-king',
            name: 'Burger King',
            latitude: 45.740905,
            longitude: 4.818946,
            description: 'Restaurant détesté de Théo',
            distanceToNiji: 600,
            type: 'fast',
            keywords: ['bk', 'king', 'burger', 'frite'],
            options: ['place', 'emporte'],
            openingDays: ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche'],
        },
        {
            id: 'intermezzo',
            name: 'Intermezzo',
            latitude: 45.743214,
            longitude: 4.815816,
            description: 'Restaurant Italien avec d\'excellentes pates',
            distanceToNiji: 750,
            type: 'restaurant',
            keywords: ['italien', 'pate', 'risotto', 'terrasse'],
            options: ['place'],
            openingDays: ['mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche'],
        },
        {
            id: 'ouest-express',
            name: 'Ouest Express',
            latitude: 45.741643,
            longitude: 4.819582,
            description: 'Fast food à la Française',
            distanceToNiji: 750,
            type: 'fast',
            keywords: ['burger', 'frite', 'pate', 'salade'],
            options: ['place', 'emporte'],
            openingDays: ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche'],
        },
        {
            id: 'my-beers',
            name: 'My Beers',
            latitude: 45.741203,
            longitude: 4.820307,
            description: 'Bar à bières avec des bons burgers',
            distanceToNiji: 850,
            type: 'bistrot',
            keywords: ['bière', 'burger', 'frite'],
            options: ['place'],
            openingDays: ['mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi'],
        },
        {
            id: 'msb',
            name: 'Mon Salade Bar',
            latitude: 45.742643,
            longitude: 4.818115,
            description: 'Bar à salade pour composer la salade de vos rêves',
            distanceToNiji: 900,
            type: 'cantine',
            keywords: ['salade'],
            options: ['emporte'],
            openingDays: ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche'],
        },
        {
            id: 'heat',
            name: 'HEAT',
            latitude: 45.737154,
            longitude: 4.819955,
            description: 'De la nouveauté',
            distanceToNiji: 1000,
            type: 'foodcourt',
            keywords: ['food', 'court', 'foodcourt'],
            options: ['place'],
            openingDays: ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche'],
        },
    ],
};
